### ISSUE TITLE
updateOption(value, data) doesn't trigger a re-render

### ISSUE THREAD

**Issue by mattgodbolt** [orchidjs/tom-select#87] opened 2021-05-15 18:59 UTC
**Describe the bug**
My option renderer uses a field in the data to customize the option's look. Calling `updateOption(value, data);` doesn't cause a re-render. I have a click handler to toggle a "is favorite" star on options.

**Expected behavior**
Ideally I could mutate the data associated with a value and then force a re-render. Calling `removeOption()` / `addOption` of the same data, or `clearCache()` or `refreshOptions()` all fail to notice the change in data and call the `render.option()` function.

**Comment by oyejorge** [comment] 2021-05-15 21:59
I think the problem is because the option still exists in the dropdown DOM ...

**Comment by oyejorge** [comment] 2021-05-15 23:09
Should be fixed now, I'll get a new release out shortly

**Comment by mattgodbolt** [comment] 2021-05-15 23:40
Wow that's amazing! Thanks!

If it's helpful, I'm currently having to both manipulate the DOM _and_ also have a render() that does the same: https://github.com/compiler-explorer/compiler-explorer/blob/d23e71c4dde76c5f6fcebdbcc15b46295b73355d/static/compiler-picker.js#L85-L124

I'm hoping I can "just" fiddle the `data` associated with an element and then say "update!". This is potentially warty as in this case I'm maipulating which groups an item is in.

**Comment by mattgodbolt** [comment] 2021-05-15 23:46
(which of course now I look at your username you _already knew_ hahah!)

**Comment by oyejorge** [comment] 2021-05-16 14:48
Just tested these tom-select changes and it's working well with the following changes to compiler-picker.js:

```js
        this.tomSelect.updateOption(value,data);
        this.tomSelect.refreshOptions(false);

        // Ensure that the favorite class is removed from the option in the case where the user
        // un-favorites from the "favorite" group itself. After the refreshOptions, the element in
        // the "Favorite" group will be removed, so this option just gets the main element itself.
        //if (!isAddingNewFavorite) {
        //    optionElement = this.tomSelect.getOption(value);
        //    optionElement.classList.remove('fav');
        //}
```

**Comment by mattgodbolt** [comment] 2021-05-17 13:21
Nice! Thanks! And thanks for the comments in the PR in compiler explorer, too!

**Closed** 2021-05-18 21:57 UTC
Labels: bug
