### ISSUE TITLE
Selecting item does not clear out typed characters

### ISSUE THREAD

**Issue by marckohlbrugge** [orchidjs/tom-select#523] opened 2022-11-17 10:23 UTC
**Bug**
Typing the first few characters and then selecting an item from the list does not clear out the typed characters.

Is this by design? It seems weird when I type `Co` and then select `Cool` from the drop down list, it inserts `Cool` but also still keeps the text `Co` in the text input.

**To Reproduce**
Create an example on JSFiddle, CodePen or similar service and outline the steps for reproducing the bug.
1. Go to https://tom-select.js.org/plugins/input-autogrow/#input-autogrow
2. Click on the input field
3. Type `co`
4. Click `Cool`
5. The input will show `Cool Co`

**Expected behavior**
I would expect it to just insert the selected item (`Cool`) without the entered text (`Co`)

This is how it works in some of the other exmaples ( https://tom-select.js.org/examples/ )

**Additional context**
 - OS: macOS 13.0.1
 - Browser: Chrome 107.0.5304.110 and Safari 16.1

**Comment by biesbjerg** [comment] 2022-12-15 10:21
As a workaround for now you can do this:

```js
const tomSelect = new TomSelect("#input", {
  onItemAdd: () => tomSelect.setTextboxValue("")
});
```

**Comment by oyejorge** [comment] 2022-12-17 01:19
Duplicate of #22

**Closed by oyejorge** 2022-12-17 01:19 UTC
Labels: bug
