### ISSUE TITLE
When clearing the textbox value after selection, dropdown on bootstrap disappears and should remain open

### ISSUE THREAD

**Issue by acetinick** [orchidjs/tom-select#146] opened 2021-07-15 16:23 UTC
**Describe the bug**

when using in event as discussion [here](https://github.com/orchidjs/tom-select/discussions/137) for clearing the type text after select , the Bootstrap 4 dropdown will disappear after selection

Previously also discussed here using tom-select inside bootstrap 4 dropdown after selection, however now its doing it after clearing the typed text.

https://github.com/orchidjs/tom-select/discussions/102

- tom-select 1.7.6
- chrome 91

**Comment by oyejorge** [comment] 2021-07-15 16:59
I saw that too. Pretty sure it's [fixed with this commit](https://github.com/orchidjs/tom-select/commit/4c3d7c08a372079f31a6c66feeca891d2121e666) but I will double check.

**Comment by oyejorge** [comment] 2021-07-15 17:33
I was wrong again and was looking at something else.

I'm not seeing the ```setTextboxValue()``` call changing anything but I am seeing the dropdown close when clicking on a option within a bootstrap dropdown.

[Does this fix the problem you're seeing](https://jsfiddle.net/fcym83hp/1/)?

**Comment by acetinick** [comment] 2021-07-20 08:08
Yep this looks like it will solve,  is there a way to bake this into the library?

**Comment by oyejorge** [comment] 2021-07-23 00:28
Couldn't figure out what was happening and realized the example above was version 1.7.2. When [tested with the latest version](https://jsfiddle.net/096svgwq/) (1.7.7), I couldn't reproduce the problem.

**Closed** 2021-08-23 21:22 UTC
Labels: bug
