### ISSUE TITLE
Safari issue with submitting selected options

### ISSUE THREAD

**Issue by acetinick** [orchidjs/tom-select#122] opened 2021-06-07 09:15 UTC
**Describe the bug**
Using safari we have strange issue with selects that have preselected options.   New options are selected and submitted fine however for some reason the options selected when editting are submitted as blank values.

![image](https://user-images.githubusercontent.com/571649/120991042-8326d180-c781-11eb-8982-330ae4acdf97.png)

More strangely is that the HTML markup looks fine.

![image](https://user-images.githubusercontent.com/571649/120990997-77d3a600-c781-11eb-9565-6448d190402b.png)

**To Reproduce**
- only with safari
- use a select with preselected option
- submit form

**Expected behavior**
- request params should contain value of selected input

**Additional context**
- safari 14.0.3,  perhaps earlier versions too
- tom-select 1.7.5, but also have tried in prior versions and same

**Comment by martinbarilik** [comment] 2021-06-07 10:16
Possibly connected to #98. Are you using latest 1.7.4 version ?

**Comment by oyejorge** [comment] 2021-06-07 19:19
Hmm, I don't know what's going on there. I just tested on safari 14 and it worked fine (single select w/ a pre-selected value). Could it be a problem with the code you're using to serialize the form data before sending it over XHR?

**Comment by oyejorge** [comment] 2021-06-09 03:59
P.S. If I could get a jsfiddle or similar that fails for you, I could test it on my safari.

**Comment by thomasklemm** [comment] 2021-07-09 21:37
Seeing the same issue in Safari, will try to create a minimal reproduction for debugging.

* tom-select 1.7.6
* Safari 14.1.1

**Comment by thomasklemm** [comment] 2021-07-09 22:18
Been able to reproduce this issue (or a similar looking one), here's a CodeSandbox: https://codesandbox.io/s/5okh7?file=/index.html // https://5okh7.csb.app/

I've recorded a 2min video about the unexpected behaviour in Safari using the CodeSandbox above: https://www.loom.com/share/0f70fd8d2dfe4bedb4d3c96be674bf61

For me the issue that the initially selected input value gets submitted happens when the select is marked as required. The select tag in @acetinick's example is also marked required, so maybe the issue is specific to selects marked as required.

**Comment by oyejorge** [comment] 2021-07-10 01:29
Thanks so much for the CodeSandbox example! I can see the problem now, there are multiple &lt;option&gt; nodes with "selected".

![Screenshot 2021-07-09 at 19-26-14 Dashboard](https://user-images.githubusercontent.com/1043524/125147899-d3c87c00-e0eb-11eb-8d00-221dbd46f0dc.png)

**Closed** 2021-07-10 05:55 UTC
Labels: bug

**Comment by oyejorge** [comment] 2021-07-10 05:56
Should be fixed now. I'll get a new release out shortly
