### ISSUE TITLE
plugins causing unexpected behaviour

### ISSUE THREAD

**Issue by braindeaf** [orchidjs/tom-select#397] opened 2022-06-08 08:38 UTC
I've been playing with TomSelect with an aim to replacing Select2 and I found some weird behaviour but only when plugins are enabled. I've pasted our code, it's not particularly remarkable but we use a few plugins and they appear to conflict with standard behaviour.

```
// TomSelect
import TomSelect from 'tom-select';
import { Controller } from "stimulus"
import { createPopper } from "@popperjs/core"

export default class extends Controller {
  connect(){
    var el = this.element
    var tags = el.getAttribute('name').match(/(tag_list|tag_id)/)
    var config = {
      onInitialize:function(){
        this.popper = createPopper(this.control, this.dropdown);
      },
      onDropdownOpen:function(){
        this.popper.update();
      },
      allowEmptyOption: true,
      // createOnBlur: true,
      createFilter: tags && function(input) {
        input = input.toLowerCase();
        return !(input in this.options);
      },
      render: {
        option: function(data, escape) {
          var div = document.createElement('div')
          div.innerHTML = data.text
          data.$option.attributes.forEach((a) => {
            div.setAttribute(a.name, a.value)
          })
          return div;
        }
      },
      // plugins: {
      //   change_listener: {},
      //   dropdown_input: {}
      // }
    };

    if (el.getAttribute('multiple')) {
      config['plugins']['remote_button'] = {
        title: 'Remove this item'
      }
    };

    new TomSelect(el, config);
  }
}

```

1. I wanted to use Popper to position our select divs so that it could cope with screen scrolling. This works, but when you enable [Dropdown Input](https://tom-select.js.org/plugins/dropdown-input) it inexplicably scrolls the page as you open the select.

![dropdown_input](https://user-images.githubusercontent.com/10952/172571712-fe64b83b-c945-4142-abee-4995fc0c5adb.gif)

2. It's important that we have empty options enabled. But I wanted to investigate how to reset all selects to the default empty state, so was playing with [Change Listener](https://tom-select.js.org/plugins/change-listener). It appears that if you have empty options enabled with change_listener that the empty option is not reset, it's just empty in fact there is no *item* div at all.

![change_listener](https://user-images.githubusercontent.com/10952/172570964-4571e90a-fc0d-4b39-b391-3a0fa24599e0.gif)

**Comment by oyejorge** [comment] 2022-06-30 04:20
(1) is a duplicate of #391

**Comment by oyejorge** [comment] 2022-07-04 03:31
(2) Not sure if I'm interpreting this one right, but if I am it doesn't sound like a bug. Best thing would be to get [a complete bug report](https://github.com/orchidjs/tom-select/issues/new?assignees=&labels=bug&template=bug_report.md&title=) including a reproducible example on jsfiddle or similar. So I'm going to close this but if it is a bug, please open a new issue with the additional info.

**Closed by oyejorge** 2022-07-04 03:31 UTC
Labels: bug
