### ISSUE TITLE
Search in Dropdown Input is not working under iOS 15

### ISSUE THREAD

**Issue by phpichler** [orchidjs/tom-select#212] opened 2021-09-23 08:53 UTC
I updated to iOS15 yesterday and noticed that the Searchfield, used within the dropdown_input Plugin can't be focused anymore.
I also tried it here: [https://tom-select.js.org/plugins/dropdown-input/]
The Input can't be focused and the Dropdown can't be searched.

I didn't figured out why this happens. Any solutions or cause so far?

Thank you for your effort.
Best Regards. Philipp

**Comment by oyejorge** [comment] 2021-09-23 14:51
Possibly a duplicate of #201

**Comment by phpichler** [comment] 2021-09-24 07:38
I don't think so, because the Problem happens since the Update to iOS 15. On iOS 14 there was no Problem. Re-Open does not solve the Problem.

**Comment by oyejorge** [comment] 2021-09-25 17:08
Can you try RC 4?

**Comment by phpichler** [comment] 2021-09-27 06:52
Sorry, i have the same Probleme with RC 4.

The same Problem is also on Tom-Select Demopage: [https://tom-select.js.org/plugins/dropdown-input/](https://tom-select.js.org/plugins/dropdown-input/)

**Comment by phpichler** [comment] 2021-10-04 13:30
Any new insights on this topic?

**Comment by oyejorge** [comment] 2021-10-04 19:44
I can't do anything till I get access to the new version. Which probably won't be till it shows up on https://live.browserstack.com

**Comment by phpichler** [comment] 2021-11-02 10:57
Any new insights on this topic? 
On iOS 15.1 the Problem still exists. I figured out that if you press the input a bit longer than a click/fingertap , the input gets focused and you can use the search. Maybe this is a new "Feature"-behavior from Safari?

**Comment by oyejorge** [comment] 2021-11-03 00:51
I was recently able to see the bug myself but I still need some time to
find a solution.

**Comment by oyejorge** [comment] 2021-11-05 13:11
It appears iOS 15 is preventing us from programmatically setting the focus on the input after [preventDefault() is called on the associated mousedown event](https://github.com/orchidjs/tom-select/blob/master/src/tom-select.ts#L357). This only appears to happen with touch  and not mouse click events.

So far however, I've been unable to solve the problem. Removing the preventDefault() isn't an option and attempting to focus the input in other ways has failed (selectRange(), setTimeout(),...)

**Comment by oyejorge** [comment] 2021-11-12 16:36
@phpichler have you had a chance to test the fix? If clicking on the input brings up the keyboard now, I think we can mark the issue as fixed.

**Comment by phpichler** [comment] 2021-11-22 13:46
Yes, it is working now. Thank you for the fix.
I'm using 1.7.5 right now. Is it possible to create a patched 1.7.9 Version? 

Nevertheless we can treat this isssue as solved and close it.

Thank you, and also thank you for this great Project.

**Closed** 2021-11-23 17:33 UTC
Labels: bug

**Comment by oyejorge** [comment] 2021-11-23 18:12
There probably won't be any more 1.7 releases. 2.0 should be pretty straight forward to migrate to, it only has [a few backward compatibility changes](https://tom-select.js.org/docs/migration/) that users typically won't have to do anything about.
